#! /usr/bin/env bash

test_description="Simple test of offlineimap sync"

. ./test-lib.sh

test_expect_success 'sanity check' '
  :
'

test_expect_failure 'offlineimap bails when config file missing' '
  offlineimap -c DOES_NOT_EXIST
'

LOCAL=test-maildir
test_begin_subtest "sync some mail"
MAIL=maildir:`pwd`/dovecot/ run_dovecot
deliver -m INBOX < $TEST_DIRECTORY/corpus/0001.txt
test_expect_equal `message_count` 0
#test_expect_equal 1 2 3 4
# echo $HOME
offlineimap
test_expect_equal `message_count` 1
kill_dovecot



test_done
